import 'dart:math' as math;

/// The shape genome of a species.
///
/// Every one of these is a slider in Tree Lab. The difference between "correct
/// L-system" and "a tree you want to look at" lives in these twenty numbers,
/// which is why they are data and why the tuning tool exists.
class BranchRules {
  const BranchRules({
    required this.maxDepth,
    required this.trunkLength,
    required this.trunkWidth,
    required this.trunkSinuosity,
    required this.lengthDecay,
    required this.taper,
    required this.branchAngleMin,
    required this.branchAngleMax,
    required this.angleJitter,
    required this.childrenPerBranch,
    required this.firstNodeAt,
    required this.apicalExtension,
    required this.phototropism,
    required this.gravityDroop,
    required this.wobble,
    required this.leafStartDepth,
    required this.leafDensity,
    required this.leafSize,
    required this.canopyBias,
    required this.asymmetry,
    this.angleDecay = 1.0,
  });

  /// Recursion depth at full maturity.
  final int maxDepth;

  final double trunkLength;
  final double trunkWidth;

  /// How much the trunk wanders off vertical. A perfectly straight trunk is
  /// the single clearest tell that a tree was generated by a computer.
  final double trunkSinuosity;

  final double lengthDecay;
  final double taper;

  /// Degrees off the parent's direction.
  final double branchAngleMin;
  final double branchAngleMax;
  final double angleJitter;

  final int childrenPerBranch;

  /// Where along the parent the first child appears, 0..1. Keeping this high
  /// leaves a clean length of trunk before the canopy starts.
  final double firstNodeAt;

  /// How far the parent continues past its last child. Apical dominance is
  /// what makes a tree read as a tree rather than as a bush of even forks.
  final double apicalExtension;

  /// Upward curl toward light, 0..1.
  final double phototropism;

  /// Downward sag, strongest on long thin branches. Birch weeps; oak does not.
  final double gravityDroop;

  /// Per-step directional noise.
  final double wobble;

  final int leafStartDepth;
  final double leafDensity;
  final double leafSize;

  /// Pushes leaf clusters toward the outside of the canopy, so the interior
  /// stays open the way a real canopy is self-shaded.
  final double canopyBias;

  final double asymmetry;

  /// Multiplies the branch angle at each successive depth.
  ///
  /// Below 1, outer branches deviate less from their parent and the canopy
  /// closes into a dome. At 1.0 every generation spreads by the same angle,
  /// which is what produces the flat umbrella silhouette that reads as
  /// "generated" rather than as a tree.
  final double angleDecay;

  double angleRangeAt(int depth) {
    final f = _pow(angleDecay, depth);
    return f;
  }

  static double _pow(double b, int e) {
    var r = 1.0;
    for (var i = 0; i < e; i++) {
      r *= b;
    }
    return r;
  }

  double get branchAngleMinRad => branchAngleMin * math.pi / 180;
  double get branchAngleMaxRad => branchAngleMax * math.pi / 180;
  double get angleJitterRad => angleJitter * math.pi / 180;

  BranchRules copyWith({
    int? maxDepth,
    double? trunkLength,
    double? trunkWidth,
    double? trunkSinuosity,
    double? lengthDecay,
    double? taper,
    double? branchAngleMin,
    double? branchAngleMax,
    double? angleJitter,
    int? childrenPerBranch,
    double? firstNodeAt,
    double? apicalExtension,
    double? phototropism,
    double? gravityDroop,
    double? wobble,
    int? leafStartDepth,
    double? leafDensity,
    double? leafSize,
    double? canopyBias,
    double? asymmetry,
    double? angleDecay,
  }) => BranchRules(
    maxDepth: maxDepth ?? this.maxDepth,
    trunkLength: trunkLength ?? this.trunkLength,
    trunkWidth: trunkWidth ?? this.trunkWidth,
    trunkSinuosity: trunkSinuosity ?? this.trunkSinuosity,
    lengthDecay: lengthDecay ?? this.lengthDecay,
    taper: taper ?? this.taper,
    branchAngleMin: branchAngleMin ?? this.branchAngleMin,
    branchAngleMax: branchAngleMax ?? this.branchAngleMax,
    angleJitter: angleJitter ?? this.angleJitter,
    childrenPerBranch: childrenPerBranch ?? this.childrenPerBranch,
    firstNodeAt: firstNodeAt ?? this.firstNodeAt,
    apicalExtension: apicalExtension ?? this.apicalExtension,
    phototropism: phototropism ?? this.phototropism,
    gravityDroop: gravityDroop ?? this.gravityDroop,
    wobble: wobble ?? this.wobble,
    leafStartDepth: leafStartDepth ?? this.leafStartDepth,
    leafDensity: leafDensity ?? this.leafDensity,
    leafSize: leafSize ?? this.leafSize,
    canopyBias: canopyBias ?? this.canopyBias,
    asymmetry: asymmetry ?? this.asymmetry,
    angleDecay: angleDecay ?? this.angleDecay,
  );

  Map<String, Object?> toJson() => {
    'maxDepth': maxDepth,
    'trunkLength': trunkLength,
    'trunkWidth': trunkWidth,
    'trunkSinuosity': trunkSinuosity,
    'lengthDecay': lengthDecay,
    'taper': taper,
    'branchAngleMin': branchAngleMin,
    'branchAngleMax': branchAngleMax,
    'angleJitter': angleJitter,
    'childrenPerBranch': childrenPerBranch,
    'firstNodeAt': firstNodeAt,
    'apicalExtension': apicalExtension,
    'phototropism': phototropism,
    'gravityDroop': gravityDroop,
    'wobble': wobble,
    'leafStartDepth': leafStartDepth,
    'leafDensity': leafDensity,
    'leafSize': leafSize,
    'canopyBias': canopyBias,
    'asymmetry': asymmetry,
    'angleDecay': angleDecay,
  };

  factory BranchRules.fromJson(Map<String, Object?> j) {
    double d(String k) => (j[k]! as num).toDouble();
    return BranchRules(
      maxDepth: (j['maxDepth']! as num).toInt(),
      trunkLength: d('trunkLength'),
      trunkWidth: d('trunkWidth'),
      trunkSinuosity: d('trunkSinuosity'),
      lengthDecay: d('lengthDecay'),
      taper: d('taper'),
      branchAngleMin: d('branchAngleMin'),
      branchAngleMax: d('branchAngleMax'),
      angleJitter: d('angleJitter'),
      childrenPerBranch: (j['childrenPerBranch']! as num).toInt(),
      firstNodeAt: d('firstNodeAt'),
      apicalExtension: d('apicalExtension'),
      phototropism: d('phototropism'),
      gravityDroop: d('gravityDroop'),
      wobble: d('wobble'),
      leafStartDepth: (j['leafStartDepth']! as num).toInt(),
      leafDensity: d('leafDensity'),
      leafSize: d('leafSize'),
      canopyBias: d('canopyBias'),
      asymmetry: d('asymmetry'),
      angleDecay: j['angleDecay'] == null ? 1.0 : d('angleDecay'),
    );
  }
}
