include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # The simulation must never be non-deterministic by accident.
    unused_import: error
    unused_local_variable: error
    dead_code: error
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_parenthesis
    - use_super_parameters
    - directives_ordering
    - omit_local_variable_types
